[package]
name = "mpc_server_1"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11.0"
base64 = "0.22.1"
ed25519-dalek = "2.2.0"
serde = "1.0.225"
solana-sdk = "3.0.0"
store = {path = "../store"}
