[package]
name = "indexer"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.28", features = ["full"] }
yellowstone-grpc-client = "9.0.0"
yellowstone-grpc-proto = "9.0.0"
futures = "0.3"
log = "0.4"
env_logger = "0.11.8"
bs58 = "0.5.0"
tonic = "0.14.2"
bytes = "1.10.1"
